/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 1;
extern const char* const kSvnInfo[1] = {"commit ac1ca0cf993e00862cfe6f6f3e302629a66e6cc3\n\
Author: lee <lee@localhost.localdomain>\n\
Date:   Fri Jan 13 02:41:23 2017 -0800\n\
\n\
    添加任务\n\
"};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Sun Jan 15 22:24:04 2017";
extern const char kBuilderName[] = "lee";
extern const char kHostName[] = "localhost.localdomain";
extern const char kCompiler[] = "GCC 4.4.7";
}}
