/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 0;
extern const char* const kSvnInfo[0] = {};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Wed Jan 11 01:12:25 2017";
extern const char kBuilderName[] = "lee";
extern const char kHostName[] = "localhost.localdomain";
extern const char kCompiler[] = "GCC 4.4.7";
}}
